---
title: "Data Analysis Notebook"
output: html_notebook
---

```{r}

#Authors: [Sydney Stanton, Carter Zborowski]

#Author Date: 06/09/2025
#Purpose: The purpose of this notebook is to house all data set transformation, cleansing, visualization, statistical analysis, and note-taking for the 2025 CU Athletic Department Sports Science Internship Program

#LAST UPDATED: 06/09/2025

#Including helpful libraries
library(tidyverse)
library(readxl)
library(aod)
library(tidyverse)
library(tidyr)
library(dplyr)
library(ggplot2)
```


## Data Cleaning 


1.ACWR- Catapult 

```{r}
ACWR <- read.csv("~/T2P1-data-analysis-2025/data-sets/ACWR- Catapult FB.csv")

#refined ACWR dataset for what I assume to be most important predictors 
Acwr <- subset(ACWR,select=c("anon_id","Position","Total.Player.Load","Acute.Total.Acceleration.Load.EWMA","Acceleration.Load.ACWR","Player.Load.ACWR","Total.Distance.ACWR"))
Acwr <- na.omit(Acwr)
```

2. Catapult Session- Outdoor 

```{r}
catapult <- read.csv("~/T2P1-data-analysis-2025/data-sets/Catapult Session - Outdoor FB.csv")

#remove periods + venues 
catapult <- catapult[,-c(16,19,20,21)]

#sort out any non football values
catapult <- catapult %>%
filter(Sport=="FOOTBALL")

#remove sport column b/c not needed anymore
catapult <- catapult[,-c(6)]

#combine date (3rd column) + athlete (2nd column // anon_id) to make an average, maximum, or sum depending on variable 
#group by (anon_id+Date), take the mean of all numerical columns 
Catapult <- catapult %>%
  group_by(anon_id, Date) %>%
  summarise(across(where(is.numeric), mean, na.rm=FALSE))
#Catapult dataset only has numerical values 
```

```{r}
#Catapult<- na.omit(Catapult)
#IMAs are counted variable so sum these
mean(catapult$High.Speed.Distance,na.rm=TRUE)
mean(catapult$Maximum.Velocity,na.rm=TRUE)
mean(catapult$Total.Player.Load,na.rm=TRUE)
mean(catapult$Player.Load.min,na.rm=TRUE)

#Maximum + average of the maximum & average velocity (given to us)
max(catapult$Maximum.Velocity,na.rm=TRUE)
mean(catapult$Average.Velocity,na.rm=TRUE)

#velocity + acceleration + deceleration + player load + IMA most important to pay attention to 
```

3. Incident Report

```{r}
incident <- read.csv("~/T2P1-data-analysis-2025/data-sets/Incident Report FB.csv")

#sort out any non football values + etc
incident <- incident %>%
filter(Sport=="FOOTBALL") %>%
filter(Incident.Type=="Injury") %>%
filter(Result.of.Sport.Participation=="Yes")

#selecting the variables of interest within the incident report
Incident <- subset(incident,select=c("anon_id", "Position", "Date.of.Injury...Onset.of.symptoms", "Side", "Body.Part", "Tissue.Type", "Pathology.Type", "OSICS14.Code", "Coach.s.Diagnosis", "OSICS10.Diagnosis", "Final.Diagnosis", "Result.of.Sport.Participation", "Recurrence.of.Injury", "Injury.Prognosis", "General.Mechanism", "Specific.Mechanism", "FinalDiagnosisIncidentDate", "Total.Time.Injured", "Month", "Year"))
```

4. Performance Normative Data

```{r}
perfnorm <- read.csv("~/T2P1-data-analysis-2025/data-sets/Performance Normative Data FB.csv")
```
```{r}
Perfnorm <- subset(perfnorm,select=c("anon_id","Date","Position","Nordic.Average","Nordic.Imbalance..","Adduction.Abduction.Ratio","Eccentric.Peak.Power...Relative","Jump.Height","Modified.RSI"))

PERFnorm <- perfnorm %>%
  group_by(anon_id, Date) %>%
  summarise(across(where(is.numeric), mean, na.rm=FALSE))

#can compare to NFL + NBA aswell
```

5.Performance Risk Assessment

```{r}
perfrisk <- read.csv("~/T2P1-data-analysis-2025/data-sets/Performance Risk Assessment FB.csv")
#ALL variables are relevant

#filter football
perfrisk <- perfrisk %>%
  filter(Sport=="FOOTBALL")

#get rid of 1(X), 10(Sport),12,13(INdexes),25
perfrisk <- perfrisk[,-c(1,10,12,13,25)]
#perfrisk <- perfrisk[,-c(53,54)]
```

6. Soft Tissue Risk Status 

```{r}
riskstatus <- read.csv("~/T2P1-data-analysis-2025/data-sets/Soft Tissue Risk Status Report FB.csv")

#refined risk status dataset contains response variable, what we are comparing against// validating 
Riskstatus <- riskstatus[,-5]

#binary could be useful when testing accuracy/importance of high risk status
Highrisk_binary=ifelse(Riskstatus$Status=="High",1,0)
#cbind(Riskstatus,Highrisk_binary)

Riskstatus$Highrisk_binary = Highrisk_binary
```

7. Strength Testing Data

```{r}
#not expected to use this dataset alot
strengthtest <- read.csv("~/T2P1-data-analysis-2025/data-sets/Strength Testing Data FB.csv")
#contains quad to hamstring strength ratio
```

8. VALD Performance Test

```{r}
VALD <- read.csv("~/T2P1-data-analysis-2025/data-sets/VALD - Performance Test FB.csv")
```

```{r}
#focus on NORDIC #s mainly
#force,power, asymmetry, difference from normative to first 

#1(X), 6-13(dates), 15-17 (notes-position)
Vald<- VALD[,-c(1,6,7,8,9,10,11,12,13,15,16,17)]
```

```{r}
#selecting variables of interest
Vald2 <- subset(VALD, select = c("anon_id", "Session.Date", "Position", "Trend", "Maximum.Force", "Percent.Difference.Norm", "Nordic.Left.MAX", "Nordic.Right.MAX", "Nordic.MEAN.Imbalance.with.side", "Positional.Norm", "Nordic...Difference.from.First.Test", "Month", "Year"))

vald2 <- Vald2 %>%
  mutate(Session.Date = as.Date(Session.Date, format = '%m/%d/%Y')) %>%
  group_by(anon_id, Month, Year, Trend) %>%
  summarise(Maximum.Force = mean(Maximum.Force, na.rm = TRUE),
            Percent.Difference.Norm = mean(Percent.Difference.Norm, na.rm = TRUE),
            Nordic.Left.MAX = mean(Nordic.Left.MAX, na.rm = TRUE),
            Nordic.Right.MAX = mean(Nordic.Right.MAX, na.rm = TRUE),
            Nordic.MEAN.Imbalance.with.side = mean(Nordic.MEAN.Imbalance.with.side, na.rm = TRUE),
            Positional.Norm = mean(Positional.Norm, na.rm = TRUE),
            Nordic...Difference.from.First.Test = mean(Nordic...Difference.from.First.Test, na.rm = TRUE)) %>%
  ungroup()
```

9. VALD Normative Report 

```{r}
#ALL variables relevant 
```

10. Wellness Report 

```{r}
wellness <- read.csv("~/T2P1-data-analysis-2025/data-sets/Wellness Report FB.csv")

#filter out non football observations
wellness <- wellness %>%
  filter(Sport=="FOOTBALL")

#mental score, physical score,sleep quality score, soreness scores, + overall wellness all relevant 
Wellness <- subset(wellness, select=c("anon_id","Date","Position","Mental.Score","Physical.Score", "Sleep.Quality.Score","Soreness.Score","Overall.Wellness.Score","Wellness.Compliance", "Month", "Year"))
```

```{r}
#omit the N/A's
Wellness2 <- Wellness %>%
  na.omit() %>%
  group_by(anon_id, Month, Year) %>%
  summarise(Mental.Score = mean(Mental.Score),
            Physical.Score = mean(Physical.Score),
            Sleep.Quality.Score = mean(Sleep.Quality.Score),
            Soreness.Score = mean(Soreness.Score),
            Overall.Wellness.Score = mean(Overall.Wellness.Score))
```

11. Merging

```{r}
#MERGE Incident and Riskstatus data sets
df <- merge(Riskstatus,Incident,by="anon_id")
```

```{r}
df <- merge(df,Perfnorm,by="anon_id")
```

```{r}
df <- merge(df,Wellness,by="anon_id")
```


## Exploratory Analysis: descriptive stats + plots


```{r}
#density plot of risk categories 
ggplot(df, aes(x=Status))+
  geom_bar(fill="lightblue")+
  labs(title="Risk Status Spread",x="Risk Status",y="Frequency")

ggplot(df, aes(x=Position))+
  geom_bar(fill="lightblue")+
  labs(title="Positional Spread",x="Players Positions",y="Frequency")

#position by status
ggplot(df,aes(x=Position,y=Status))+  #scatterplot
  geom_point()+
  geom_jitter()+ 
  labs(title="Position Influence on Hamstring Risk Status",y="Risk Status")

ggplot(df,aes(x=Position,fill=Status))+   #stacked bar chart
  geom_bar(inherit.aes = TRUE)+
  scale_fill_brewer()
```
```{r}
#density plot of Body. part density 
ggplot(df, aes(x=Body.Part))+
  geom_bar(fill="lightblue")+
  labs(title="Part of Body INjured Spread",x="Injured Body Part",y="Frequency")

ggplot(df, aes(x=Recurrence.of.Injury))+
  geom_bar(fill="lightblue")+
  labs(title="Recurrence of Injury Spread",x="Injury Recurrence",y="Frequency")


#injury rate by risk category (Riskstatus)
#injury rate by previous injury history

#distributions of strength/imbalance by risk category 
#boxplot(y~`Status,data=df)
```


```{r}
#risk category validity checks 
```


```{r}
#correlation checks 

```


```{r}

```


## Validating the Soft-Tissue Watchlist


```{r}
#filtering just the high risk athletes from the watchlist
Riskstatus_high <- Riskstatus %>%
  filter(Status == 'High') %>%
  mutate(Date = as.Date(Date, format = '%m/%d/%Y')) %>%
  arrange(Date) %>%
  group_by(anon_id) %>%
  summarize(DateRisk = paste0(Date, collapse = " and "))

#creating a list of the unique athlete ids that were deemed high risk
high_risk <- unique(Riskstatus_high$anon_id)
```

```{r}
#creating a list of the lower body areas in Body.Part and for OSICS codes for HSI
lower_body <- c("Thigh", "Ankle", "Lower Leg", "Knee", "Foot", "Groin/hip")
hamstring_OSICS14 <- c('TM1', 'TMB', 'TMS', 'TR1')

#filtering the incident report to only show those deemed high risk with only lower body injuries as well as only HSI related injuries
incident_hr_all <- Incident %>%
  filter(anon_id %in% high_risk, Body.Part %in% lower_body) %>%
  group_by(anon_id, Date.of.Injury...Onset.of.symptoms) %>%
  mutate(Total.Time.Injured = sum(Total.Time.Injured, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(across(everything())) %>%
  summarise(.groups = 'drop')

incident_hr_HSI <- Incident %>%
  filter(anon_id %in% high_risk, OSICS14.Code %in% hamstring_OSICS14) %>%
  group_by(anon_id, Date.of.Injury...Onset.of.symptoms) %>%
  mutate(Total.Time.Injured = sum(Total.Time.Injured, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(across(everything())) %>%
  summarise(.groups = 'drop')

#consolidates all injuries for these athletes into one column
incident_hr_all2 <- incident_hr_all %>%
  mutate(Date = as.Date(Date.of.Injury...Onset.of.symptoms, format = '%m/%d/%Y')) %>%
  arrange(Date) %>%
  group_by(anon_id) %>%
  summarize(Outcome = paste0(FinalDiagnosisIncidentDate, collapse = " and "))

incident_hr_HSI2 <- incident_hr_HSI %>%
  mutate(Date = as.Date(Date.of.Injury...Onset.of.symptoms, format = '%m/%d/%Y')) %>%
  arrange(Date) %>%
  group_by(anon_id) %>%
  summarize(Outcome = paste0(FinalDiagnosisIncidentDate, collapse = " and "))
```

```{r, warning = FALSE}
#combines the dates the athletes were deemed high risk with their injuries and separates the injury occurrences and dates
validation_all <- left_join(Riskstatus_high, incident_hr_all2, by = 'anon_id') %>%
  separate(Outcome, c('Injury.1', 'Injury.2', 'Injury.3', 'Injury.4', 'Injury.5', 'Injury.6', 'Injury.7', 'Injury.8'), sep = ' and ') %>%
  separate(DateRisk, c('Test.1', 'Test.2'), sep = ' and ')

#combines the above but specifically for HSI and includes T/F for whether the athlete suffered their injury after their high risk assessment
validation_HSI <- left_join(Riskstatus_high, incident_hr_HSI2, by = 'anon_id') %>%
  separate(Outcome, c('Injury.1', 'Injury.2', 'Injury.3', 'Injury.4'), sep = ' and ') %>%
  separate(DateRisk, c('Test.1', 'Test.2'), sep = ' and ')

validation_HSI <- validation_HSI %>%
  mutate(Injury.1.After = as.Date(str_sub(validation_HSI$Injury.1, start = -10), format = '%m/%d/%Y') > Test.1,
         Injury.2.After = as.Date(str_sub(validation_HSI$Injury.2, start = -10), format = '%m/%d/%Y') > Test.1,
         Injury.3.After = as.Date(str_sub(validation_HSI$Injury.3, start = -10), format = '%m/%d/%Y') > Test.1,
         Injury.4.After = as.Date(str_sub(validation_HSI$Injury.4, start = -10), format = '%m/%d/%Y') > Test.1,
         Injury.1.After.2 = as.Date(str_sub(validation_HSI$Injury.1, start = -10), format = '%m/%d/%Y') > Test.2,
         Injury.2.After.2 = as.Date(str_sub(validation_HSI$Injury.2, start = -10), format = '%m/%d/%Y') > Test.2,
         Injury.3.After.2 = as.Date(str_sub(validation_HSI$Injury.3, start = -10), format = '%m/%d/%Y') > Test.2,
         Injury.4.After.2 = as.Date(str_sub(validation_HSI$Injury.4, start = -10), format = '%m/%d/%Y') > Test.2)
         
#adds columns that return 'Yes' if an injury occurred after the athlete was deemed high risk and a 'No' if no injury occurred after
validation_HSI <- validation_HSI %>%
         mutate(Test.1.Success = ifelse(rowSums(validation_HSI[, c('Injury.1.After', 'Injury.2.After', 'Injury.3.After', 'Injury.4.After')], na.rm = TRUE) > 0, 'Yes', 'No'),
         Test.2.Success = ifelse(is.na(validation_HSI$Test.2), NA, ifelse(rowSums(validation_HSI[, c('Injury.1.After.2', 'Injury.2.After.2', 'Injury.3.After.2', 'Injury.4.After.2')], na.rm = TRUE) > 0, 'Yes', 'No')))
```

```{r}
#combining tests and injury outcomes and creating a data frame that just contains the dates of the test results and whether an injury occurred for the athlete after these tests
tests <- c(validation_HSI$Test.1, validation_HSI$Test.2)
outcomes <- c(validation_HSI$Test.1.Success, validation_HSI$Test.2.Success)
tests_outcomes <- data.frame(tests, outcomes) %>%
  na.omit

#calculating percent of the time right
mean(tests_outcomes$outcomes == 'Yes')

#visualizing using a bar plot 
ggplot(tests_outcomes, aes(x = outcomes, fill = outcomes)) + 
  geom_bar(color = 'black', show.legend = FALSE) +
  scale_fill_manual(values = c('gold2', 'grey2')) + 
  labs(title = 'Outcomes of Soft Tissue Watchlist (High Risk)',
       x = 'Injury Occured After Deemed High Risk',
       y = 'Number of Observations') + 
  theme_bw()
```